apiVersion: v1
kind: Service
metadata:
  name: db-service
  # if name is changed, adjust the configmap "phonebook-cm" as well
  labels:
    name: mysql
    app: phonebook
spec:
  selector:
    name: mysql
  type: ClusterIP
  ports:
  - name: db
    port: 3306
    targetPort: 3306