apiVersion: v1
kind: Service
metadata:
  name: result-server-service
  labels:
    name: search
    app: phonebook
spec:
  selector:
    app: phonebook
    name: search
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30002
    protocol: TCP