apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-server-deployment
  labels:
    name: search
    app: phonebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonebook
  template:
    metadata:
      labels:
        name: search
        app: phonebook
    spec:
      restartPolicy: Always
      containers:
      - image: simaox/phonebook_2
        name: bookstore-app-2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # envFrom:
        #   - secretRef: 
        #       name: my-db-passwords
        #   - configMapRef:
        #       name: phonebook-cm
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: phonebook-cm
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: phonebook-cm
                key: MYSQL_USER
          - name: MYSQL_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: phonebook-cm
                key: MYSQL_DATABASE_HOST
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-db-passwords
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-db-passwords
                key: MYSQL_ROOT_PASSWORD