apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  labels:
    name: create-delete-update
    app: phonebook
spec:
  selector:
    app: phonebook
    name: create-delete-update
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP